name: outmoded-model-engine
version: '1.0-alpha'
main: net.outmoded.modelengine.ModelEngine
api-version: '1.21'
author: DRAGNIL68
commands:
  animated-skript:
    description: Insert Funny Text Here
    usage: /animated-skript help
    permission: animated-skript