name: Animated-Skript
version: '1.0-test1'
main: net.outmoded.animated_skript.AnimatedSkript
softdepend: [Skript]
api-version: '1.21'
author: DRAGNIL68
commands:
  animated-skript:
    description: Insert Funny Text Here
    usage: /animated-skript help
    permission: animated-skript.see_command

animated-skript:
  description: Allows a player to use all animated-skript commands
  default: op
