name: Animated-Skript
version: '1.3-alpha'
main: net.outmoded.modelengine.ModelEngine
depend: [Skript]
api-version: '1.21'
author: DRAGNIL68
commands:
  animated-skript:
    description: Insert Funny Text Here
    usage: /animated-skript help
    permission: animated-skript