name: outmoded-model-engine
version: '1.0-alpha'
main: net.outmoded.modelengine.ModelEngine
api-version: '1.21'
author: DRAGNIL68
commands:
  model_engine:
    description: Insert Funny Text Here
    usage: /model_engine [arg]
    permission: model_engine