name: Animated-Skript
version: '1.4.1-alpha'
main: net.outmoded.animated_skript.AnimatedSkript
depend: [Skript]
api-version: '1.21'
author: DRAGNIL68
commands:
  animated-skript:
    description: Insert Funny Text Here
    usage: /animated-skript help
    permission: animated-skript